openapi: 3.1.0
info:
  title: ナレッジ管理API
  description: Retrieves current weather data for a location.
  version: v1.0.0
servers:
  - url: https://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev
paths:
  /open_github_repo:
    post:
      description: get README and description of a Github repository
      operationId: openGithubRepo
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                repo_name:
                  type: string
                  description: Github repository name (e.g. tatsuiman/slack-copilot)
                github_token:
                  type: string
                  description: "GITHUB_TOKEN=xxxxx"
              required:
                - repo_name
                - github_token
  /github_fetch_pull_requests:
    post:
      description: fetch pull requests from a Github repository
      operationId: githubFetchPullRequests
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                repo_name:
                  type: string
                  description: Github repository name (e.g. tatsuiman/slack-copilot)
                github_token:
                  type: string
                  description: "GITHUB_TOKEN=xxxxx"
                status:
                  type: string
                  description: "Status of the pull request (open, closed)"
                  default: open
              required:
                - repo_name
                - github_token
  /open_github_url:
    post:
      description: open a specified URL and retrieve its content
      operationId: openGithubUrl
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: Github URL to open (PR, Issue, Code, etc.)
                github_token:
                  type: string
                  description: "GITHUB_TOKEN=xxxxx"
              required:
                - url
                - github_token
  /github_trending:
    post:
      description: retrieve trending repositories from Github
      operationId: githubTrending
      x-openai-isConsequential: false
      tags:
        - Retrieve
        - Trending
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                  description: 'Language ('''': all languages)'
                since:
                  type: string
                  description: Since (daily, weekly, monthly)
              required:
                - language
                - since
  /github_search:
    post:
      description: search within GitHub for Issues, Pull Requests, and code
      operationId: githubSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords to search for (e.g. 'openai slack')
                github_token:
                  type: string
                  description: "GITHUB_TOKEN=xxxxx"
                lang:
                  type: string
                  description: 'Language (None: all languages)'
                org:
                  type: string
                  description: 'GitHub organization name (None: all organizations)'
              required:
                - keyword
                - github_token
  /get_github_discussion:
    post:
      description: retrieve discussion list from a Github Discussion URL
      operationId: getGithubDiscussion
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the Github Discussion
                github_token:
                  type: string
                  description: "GITHUB_TOKEN=xxxxx"
              required:
                - url
                - github_token
components:
  schemas: {}
