openapi: 3.1.0
info:
  title: 緯度経度
  description: Retrieves current weather data for a location.
  version: v1.0.0
servers:
  - url: https://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev
paths:
  /location_search:
    post:
      description: search for location x,y,z
      operationId: locationSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Address to search (e.g. '東京都品川区')
                zoom:
                  type: integer
                  description: Zoom level (13~15)
              required:
                - keyword
                - zoom
components:
  schemas: {}
