openapi: 3.1.0
info:
  title: ナレッジ管理API
  description: Retrieves current weather data for a location.
  version: v1.0.0
servers:
  - url: https://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev
paths:
  /create_notion_page:
    post:
      description: create a page in Notion with specified title and content
      operationId: createNotionPage
      x-openai-isConsequential: false
      tags:
        - Create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the page
                content:
                  type: string
                  description: Content of the page
                notion_secret:
                  type: string
                  description: "NOTION_SECRET=xxxxx"
                database_id:
                  type: string
                  description: "NOTION_DATABASE_ID=xxxxx"
              required:
                - title
                - content
                - notion_secret
                - database_id
  /notion_search:
    post:
      description: search within Notion pages and databases
      operationId: notionSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords to search for
                notion_secret:
                  type: string
                  description: "NOTION_SECRET=xxxxx"
              required:
                - keyword
                - notion_secret
  /open_notion_url:
    post:
      description: retrieve content from a Notion page using NotionAPI
      operationId: getNotionContent
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the Notion page
                notion_secret:
                  type: string
                  description: "NOTION_SECRET=xxxxx"
              required:
                - url
                - notion_secret
  /append_notion_page:
    post:
      description: append content to a Notion page
      operationId: appendNotionPage
      x-openai-isConsequential: false
      tags:
        - Append
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page_id:
                  type: string
                  description: ID of the Notion page
                content:
                  type: string
                  description: Content to append
                notion_secret:
                  type: string
                  description: "NOTION_SECRET=xxxxx"
              required:
                - page_id
                - content
                - notion_secret
components:
  schemas: {}
