openapi: 3.1.0
info:
  title: ナレッジ管理API
  description: Retrieves current weather data for a location.
  version: v1.0.0
servers:
  - url: https://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev
paths:
  /create_notion_page:
    post:
      description: create a page in Notion with specified title and content
      operationId: createNotionPage
      x-openai-isConsequential: false
      tags:
        - Notion
        - Create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the page
                content:
                  type: string
                  description: Content of the page
              required:
                - title
                - content
  /append_notion_page:
    post:
      description: append content to a Notion page
      operationId: appendNotionPage
      x-openai-isConsequential: false
      tags:
        - Notion
        - Update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page_id:
                  type: string
                  description: Notion page id
                content:
                  type: string
                  description: Content to append
              required:
                - page_id
                - content
  /open_slack_url:
    post:
      description: retrieve message list from a Slack URL
      operationId: getSlackMessages
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the Slack thread
              required:
                - url
  /open_notion_url:
    post:
      description: retrieve content from a Notion page using NotionAPI
      operationId: getNotionContent
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the Notion page
              required:
                - url
  /open_url:
    post:
      description: open a specified URL and retrieve its content
      operationId: getUrlContent
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL to open
              required:
                - url
  /open_slack_canvas_url:
    post:
      description: retrieve content from a slack canvas URL
      operationId: getSlackCanvasContent
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: slack canvas URL
              required:
                - url
  /google_drive_search:
    post:
      description: search for file names in Google Drive
      operationId: googleDriveSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords to search for
              required:
                - keyword
  /slack_search:
    post:
      description: search message history in Slack
      operationId: slackSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords or phrases to search for
              required:
                - keyword
  /notion_search:
    post:
      description: search within Notion pages and databases
      operationId: notionSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords to search for
              required:
                - keyword
  /open_github_repo:
    post:
      description: get README and description of a Github repository
      operationId: openGithubRepo
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                repo_name:
                  type: string
                  description: Github repository name (e.g. tatsuiman/slack-copilot)
              required:
                - repo_name
  /open_github_url:
    post:
      description: open a specified URL and retrieve its content
      operationId: openGithubUrl
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: Github URL to open (PR, Issue, Code, etc.)
              required:
                - url
  /github_search:
    post:
      description: search within GitHub for Issues, Pull Requests, and code
      operationId: githubSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords to search for (e.g. 'openai slack')
                lang:
                  type: string
                  description: 'Language (None: all languages)'
                org:
                  type: string
                  description: 'GitHub organization name (None: all organizations)'
              required:
                - keyword
  /google_search:
    post:
      description: search within Google
      operationId: googleSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keyword using Google Hacking Techniques.(e.g. 'site:twitter.com')
              required:
                - keyword
  /trend_search:
    post:
      description: generate trend search urls
      operationId: trendSearch
      x-openai-isConsequential: false
      tags:
        - Search
        - Trends
        - SNS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keywords:
                  type: string
                  description: Keywords combined with a comma (e.g. openai,gemini)
              required:
                - keywords
  /arxiv_search:
    post:
      description: Paper search within arXiv
      operationId: arxivSearch
      x-openai-isConsequential: false
      tags:
        - Search
        - Paper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Query using arXiv search.(e.g. 'quantum' 'au:del_maestro AND ti:checkerboard')
              required:
                - query
  /youtube_search:
    post:
      description: search within Youtube
      operationId: youtubeSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keyword using Youtube search.
              required:
                - keyword
  /get_github_discussion:
    post:
      description: retrieve discussion list from a Github Discussion URL
      operationId: getGithubDiscussion
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the Github Discussion
              required:
                - url
  /fact_checker:
    post:
      description: check the veracity of claims or news using Google's Fact Check Tools API
      operationId: factCheck
      x-openai-isConsequential: false
      tags:
        - Check
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Enter your search query here. English only
              required:
                - query
  /intelx_search:
    post:
      description: Search Tor, I2P, data leaks and the public web by email, domain, IP, CIDR, Bitcoin address and more
      operationId: intelxSearch
      x-openai-isConsequential: false
      tags:
        - Search
        - Security
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords to search for
              required:
                - keyword
  /ingest_memory:
    post:
      description: ingest memory
      operationId: ingestMemory
      x-openai-isConsequential: false
      tags:
        - Ingest
        - Memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Text to ingest
              required:
                - text
  /semantic_search_memory:
    post:
      description: semantic search memory
      operationId: semanticSearchMemory
      x-openai-isConsequential: false
      tags:
        - Search
        - Memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Query to semantic search
              required:
                - query
  /convert_mermaid_to_imgur:
    post:
      description: convert mermaid to imgur
      operationId: convertMermaidToImgur
      x-openai-isConsequential: false
      tags:
        - Convert
        - Mermaid
        - Imgur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                script:
                  type: string
                  description: Mermaid script
              required:
                - script
components:
  schemas: {}
