openapi: 3.1.0
info:
  title: ナレッジ管理API
  description: Retrieves current weather data for a location.
  version: v1.0.0
servers:
  - url: https://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev
paths:
  /open_url:
    post:
      description: open a specified URL and retrieve its content
      operationId: getUrlContent
      x-openai-isConsequential: false
      tags:
        - Retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL to open
              required:
                - url
  /trend_search:
    post:
      description: generate trend search urls
      operationId: trendSearch
      x-openai-isConsequential: false
      tags:
        - Search
        - Trends
        - SNS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keywords:
                  type: string
                  description: Keywords combined with a comma (e.g. openai,gemini)
              required:
                - keywords
  /arxiv_search:
    post:
      description: Paper search within arXiv
      operationId: arxivSearch
      x-openai-isConsequential: false
      tags:
        - Search
        - Paper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Query using arXiv search.(e.g. 'quantum' 'au:del_maestro AND ti:checkerboard')
              required:
                - query
  /youtube_search:
    post:
      description: search within Youtube
      operationId: youtubeSearch
      x-openai-isConsequential: false
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keyword using Youtube search.
              required:
                - keyword
  /fact_checker:
    post:
      description: check the veracity of claims or news using Google's Fact Check Tools API
      operationId: factCheck
      x-openai-isConsequential: false
      tags:
        - Check
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Enter your search query here. English only
              required:
                - query
  /intelx_search:
    post:
      description: Search Tor, I2P, data leaks and the public web by email, domain, IP, CIDR, Bitcoin address and more
      operationId: intelxSearch
      x-openai-isConsequential: false
      tags:
        - Search
        - Security
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  description: Keywords to search for
                intelx_api_key:
                  type: string
                  description: "INTELX_API_KEY=xxxxxxx"
              required:
                - keyword
                - intelx_api_key
  /ingest_memory:
    post:
      description: ingest memory
      operationId: ingestMemory
      x-openai-isConsequential: false
      tags:
        - Ingest
        - Memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Text to ingest
              required:
                - text
  /semantic_search_memory:
    post:
      description: semantic search memory
      operationId: semanticSearchMemory
      x-openai-isConsequential: false
      tags:
        - Search
        - Memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Query to semantic search
              required:
                - query
  /convert_mermaid_to_imgur:
    post:
      description: convert mermaid to imgur
      operationId: convertMermaidToImgur
      x-openai-isConsequential: false
      tags:
        - Convert
        - Mermaid
        - Imgur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                script:
                  type: string
                  description: Mermaid script
                imgur_client_id:
                  type: string
                  description: "IMGUR_CLIENT_ID=xxxxxxx"
              required:
                - script
                - imgur_client_id
components:
  schemas: {}
