name: Deploy to AWS Lambda - Development Environment

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - '.github/workflows/develop.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install serverless and plugins
      run: |
        npm install -g serverless
        serverless plugin install -n serverless-api-gateway-throttling
        serverless plugin install -n serverless-prune-plugin
    - name: Install dependencies
      run: npm install
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: sls deploy -s dev
